### ISSUE TITLE
Private constants as default arguments - Swift 4 Support

### ISSUE THREAD

**Issue by eaceto** [auth0/Guardian.swift#61]
# Problem

When adding Guardian to a project that uses Swift 4.x, there are several errors building Guardian pod. All of them refer to the fact that an internal constant (let) cannot be referenced from a default argument value.

The constant is:

```
let nonCachedSession: URLSession =  {
     let config = URLSessionConfiguration.default
     config.requestCachePolicy = .reloadIgnoringLocalCacheData
     config.urlCache = nil

     return URLSession.init(configuration: config)
}()
```

_Guardian.swift  line 25_

And some of the places where it is used as default value are:

```
public func api(forDomain domain: String, session: URLSession = nonCachedSession) -> API {
    return api(url: url(from: domain)!, session: session)
}
```

_Guardian.swift  line 47_

# Workaround:

    In the Pods project change the default language to Swift 3 (or below). 

# Fix:

    Make nonCachedSession public

# Screenshots

## Swift 3

![captura de pantalla 2018-07-02 a la s 17 56 56](https://user-images.githubusercontent.com/870528/42186449-200ac9d0-7e23-11e8-8a68-50dc89e27936.png)

## Swift 4.x

![captura de pantalla 2018-07-02 a la s 18 10 55](https://user-images.githubusercontent.com/870528/42186506-58c82f56-7e23-11e8-821b-7cdeed4973d9.png)

**Comment by hzalaz** [comment]
Closed by #63
