### ISSUE TITLE
[Cocoapods] podspec not updated to the latest project release (1.1.0)

### ISSUE THREAD

**Issue by aaresu** [auth0/Guardian.swift#95]
Even if the README.md has been updated reporting the lastest version in the I the installation instruction:
https://github.com/auth0/Guardian.swift#cocoapods

the Guardian.podspec has not been updated accordingly referring to the correct version and of course, can't be pushed to the Cocoapods specs repo.

**Comment by ObidosDev** [comment]
@zgordon02 
`pod 'Guardian', :git => 'https://github.com/auth0/Guardian.swift.git', :tag => '1.1.0'`

**Comment by ionutmanolache-okta** [comment]
The iOS Swift SDK v1.2.0 has been released recently:
GitHub:[Release 1.2.0 · auth0/Guardian.swift](https://github.com/auth0/Guardian.swift/releases/tag/1.2.0)
Cocoapods: [Guardian](https://cocoapods.org/pods/Guardian)
